server:
  port: 2020
  servlet:
    context-path: /

spring:
  application:
    name: doinb-demo-service
  profiles:
    active: dev
logging:
  level:
    org.springframework.boot.web.embedded.tomcat: debug
